# Generated by Django 5.2 on 2026-09-07 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=40)),
                ('favorites', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activities')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.user')),
            ],
        ),
        migrations.CreateModel(
            name='RecentActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=40)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('approx_location', models.CharField(default=None, max_length=40)),
                ('group_size', models.IntegerField()),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activities')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_message', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('read_message', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.user')),
            ],
        ),
    ]
