# Generated by Django 5.2 on 2026-09-20 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'ordering': ['activity_name']},
        ),
        migrations.RemoveField(
            model_name='activities',
            name='favorites',
        ),
        migrations.AddField(
            model_name='recommendations',
            name='recommendation_name',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='read_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recentactivities',
            name='approx_location',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='recentactivities',
            name='group_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('friendslist_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.user')),
            ],
        ),
    ]
