# Generated by Django 5.2 on 2026-09-27 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activities_options_remove_activities_favorites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='friendslist_id',
        ),
        migrations.AddField(
            model_name='friends',
            name='friend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friend_of', to='activities.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friends',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships', to='activities.user'),
        ),
    ]
