# Generated by Django 5.2 on 2026-09-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_friends_friendslist_id_friends_friend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='category',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
