"""
Django settings for Knit_Application project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# ================================================================================================
# 0) CORE IMPORTS
# ================================================================================================

from pathlib import Path
from Knit_Application.secret_environments import env


# ================================================================================================
# 1) BASE DIRECTORY
# ================================================================================================

BASE_DIR = Path(__file__).resolve().parent.parent.parent
# added third parent for updated path


# ================================================================================================
# 2) SECURITY SETTINGS
# ================================================================================================

SECRET_KEY = env('SECRET_KEY') # need to import secret_environments file

# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = []

# ================================================================================================
# 3) SITE_ID  (NEW CHANGES)
# ================================================================================================

SITE_ID = 1

# ================================================================================================
# 4) APPLICATION DEFINITION (NEW CHANGES)
# ================================================================================================


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",                  # <--- Added for Vega-Lite & public API
    "activities",

    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]
# ================================================================================================
# 5) Authentication Backends  (NEW CHANGES)
# ================================================================================================

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# ================================================================================================
# 6) MIDDLEWARE (NEW CHANGES)
# ================================================================================================

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # New Addition for Assignment 5 Part 3.1
    'allauth.account.middleware.AccountMiddleware',  # New Changes/Addition

    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ================================================================================================
# 7) URL CONFIGURATION
# ================================================================================================


ROOT_URLCONF = "Knit_Application.urls"

# ================================================================================================
# 7) template CONFIGURATION
# ================================================================================================


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ================================================================================================
# 9) WSGI
# ================================================================================================


WSGI_APPLICATION = "Knit_Application.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / 'data' "db.sqlite3",
    } # updated path for sqlite, in data folder
}

# ================================================================================================
# 10) PASSWORD VALIDATION
# ================================================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ================================================================================================
# 11) INTERNATIONALIZATION
# ================================================================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# ================================================================================================
# 12) DEFAULT PRIMARY KEY FIELD TYPE
# ================================================================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ================================================================================================
# 13) STATIC FILES CONFIGURATION
# ================================================================================================


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

STATICFILES_DIRS = [BASE_DIR / "Knit_Application/Knit_Application/ui-ux/static"]
STATIC_ROOT = BASE_DIR / "Knit_Application/ui-ux/staticfiles"
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

# ================================================================================================
# 14) AUTHENTICATION / LOGIN CONFIGURATION
# ================================================================================================


LOGIN_URL = "login_urlpattern"        # where to send people if not logged in

# Where the users are directed after login
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login_urlpattern'

# ================================================================================================
# 15) GOOGLE LOGIN TEMPLATE (NEW CHANGES)
# ================================================================================================

SOCIALACCOUNT_LOGIN_ON_GET = True

# ================================================================================================
# 16) CORS CONFIGURATION (Required for Public API & Vega-Lite) (NEW CHANGES)
# ================================================================================================

CORS_ALLOW_ALL_ORIGINS = True